### ISSUE TITLE
Map inputs to send to the games

### ISSUE THREAD

**Issue by eipeipkrop7992** [SleepKiller/dinput8_hook#1]
Hi,

You have a great project!
I would like to integrate with mine which consist in playback mouse and keyboard inputs through hooking dll inside of the games. It is simple:
1 - I already grab a bunch of inputs (in other screen/desktop).
2 - I receive all them by websocket.

So, I ask you how can I map into you code, as an example, the "A" (keyboard) which must be to send to game?

**Comment by SleepKiller** [comment]
It depends on what API the game uses to get it's input. 

In the case of DirectInput a simple method would be to hook [GetDeviceState](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.idirectinputdevice8.idirectinputdevice8.getdevicestate(v=vs.85).aspx) and edit the state in the hook before it's returned to the game.

I've written up an untested example of doing this and posted it [here](https://gist.github.com/SleepKiller/8cd76f3b8bab34bef128e2b4177d1db3). 

However if the game uses normal Win32 apis to get it's input things are a lot simpler. (And should be able to be done from a separate process without hooking.) You can use FindWindow to get the HWND of the game's window and then use SendInput or PostMessage on the window. I'd imagine you can find examples of doing this around the net.
